<a href="https://colab.research.google.com/github/abhigya-08/math/blob/main/workshop6ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Name: Abhigya Maharjan**

**University id: 2595463**

Part 1

problem 1

In [2]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[7,8,9]], dtype = float)
print(arr)
print(arr.dtype)
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.itemsize)
print(arr.nbytes)
print(arr.flags)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
float64
2
(3, 3)
9
8
72
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



problem 2

In [3]:
import numpy as np
arr = 3 * np.ones((4,5), dtype = float)
print(arr)
print(arr.shape)
print(arr.dtype)

[[3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]]
(4, 5)
float64


problem 3

In [6]:
import numpy as np
arr = np.full((4,5),3,dtype=float)
print(arr)
print(arr.shape)
print(arr.dtype)

[[3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]]
(4, 5)
float64


problem 4

In [7]:
import numpy as np
arr = np.fromfunction(lambda i, j: np.abs(i+1-3*(j+1))/2, (3,3), dtype=int)
print(arr)
print(arr.shape)
print(arr.dtype)

[[1.  2.5 4. ]
 [0.5 2.  3.5]
 [0.  1.5 3. ]]
(3, 3)
float64


problem 5

In [10]:
import numpy as np
arr = np.diag([1,2,3,4], k=0)
print(arr)
print(arr.shape)
print(arr.dtype)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
(4, 4)
int64


problem 6

In [16]:
import numpy as np
arr = np.random.randint(0,20,(4,5))
print(arr)
new_arr = arr[:3, :3]
print(new_arr)

[[17  0  4  6  5]
 [ 9  1 17 15 15]
 [13  1 10 18  5]
 [14 12  0  4  5]]
[[17  0  4]
 [ 9  1 17]
 [13  1 10]]


Part 2

problem 1

In [19]:
import numpy as np
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
B = np.array([[1,1,1],[2,2,2]])
C = A + b
print(A)
print(B)
print(C)

NameError: name 'b' is not defined

problem 2

In [24]:
import numpy as np
def dot_product(vect1, vect2):
  vect1 = vect1.flatten()
  vect2 = vect2.flatten()
  return np.sum(np.multiply(vect1,vect2))
def matrix_vector_product(mat,vec):
  m,n = mat.shape
  p,q = vec.shape

  assert n==p, "the matrix and vector are not compatible for multiplication"

  result = np.zeros((m,q),dtype=float)

  for i in range(m):
    result[i] = dot_product(mat[i,:],vec)
  return result

mat1 = np.full((3,3), 3, dtype=int)
vec1 = np.full((3,1), 2, dtype=int)
print(mat1)
print(vec1)
result1 = matrix_vector_product(mat1,vec1)
print(result1)
result2 = mat1 @ vec1
print(result2)


[[3 3 3]
 [3 3 3]
 [3 3 3]]
[[2]
 [2]
 [2]]
[[18.]
 [18.]
 [18.]]
[[18]
 [18]
 [18]]


problem 3

In [28]:
import numpy as np
A = np.array([[1,2],[3,4]])
B = np.array([[1,2],[3,4]])
C = np.dot(A,B)
print(C)

[[ 7 10]
 [15 22]]


problem 4

In [33]:
import numpy as np
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
if(A.T == A).all():
    print("Symmetric")
else:
    print("Not Symmetric")


Not Symmetric
